variable "name" {
    type = string
    description = "Name your VM (Required)"
}

variable "machine_type" {
    type = string
    default = "e2-medium"
    description = "Machine type. Default is e2-medium"
}

variable "zone" {
    type = string
    default = "europe-west3-a"
    description = "VM zone. Default is europe-west3-a"
}

variable "vm_image" {
    type = string
    default = "ubuntu-os-cloud/ubuntu-2204-lts"
    description = "Image (Operational System for the VM) Default is Ubuntu-2204-lts"
}

variable "size" {
    type = number
    default = 32
    description = "VM boot disk size"
}

variable "network_id" {
    type = string
    description = "Network id (Also known as VPC or Vlan)"
}

variable "subnet_id" {
    type = string
    description = "Subnet Id where the vm will be placed"
}

variable "tags" {
    type = list 
    default = [ "terraform-vm" ]
    description = "VM tags"
}

variable "public_ip" {
    type = string
    default = null
    description = "Public adress generated by address resource"  
}

variable "ssh_keys" {
    type = string
    description = "Keys to access the image"
}

